# Generated by Django 5.0.4 on 2024-04-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_recombooks_drcode_remove_recombooks_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recombooks',
            name='drcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recombooks',
            name='keyword',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='recombooks',
            name='recomment',
            field=models.CharField(default='없음', max_length=2000),
        ),
        migrations.AddField(
            model_name='recombooks',
            name='recomno',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='recombooks',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recombooks',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='BookDetails',
        ),
    ]
