# Generated by Django 5.0.4 on 2024-04-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_recombooks_drcode_remove_recombooks_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recombooks',
            name='drcode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recombooks',
            name='isbn',
            field=models.CharField(default='9700000000000', max_length=13),
        ),
        migrations.AddField(
            model_name='recombooks',
            name='publisher',
            field=models.CharField(default='알수없음', max_length=8),
        ),
        migrations.AddField(
            model_name='recombooks',
            name='recomment',
            field=models.CharField(default='없음', max_length=2000),
        ),
        migrations.AddField(
            model_name='recombooks',
            name='recomno',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.DeleteModel(
            name='BookDetails',
        ),
    ]
