# Generated by Django 4.2.11 on 2024-04-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recombooks',
            name='keyword',
            field=models.JSONField(default=list, max_length=2000),
        ),
    ]
