# Generated by Django 5.0.4 on 2024-04-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecomBooks',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('recomment', models.CharField(max_length=2000)),
                ('recomisbn', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomno', models.BigIntegerField(default=20000000000000000000)),
                ('drcode', models.PositiveIntegerField(default=0)),
                ('publisher', models.CharField(max_length=15)),
                ('recom_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.recombooks')),
            ],
        ),
    ]
