# Generated by Django 5.0.4 on 2024-04-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='publisher',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='recomno',
            field=models.CharField(max_length=20),
        ),
    ]
