# Generated by Django 5.0.4 on 2024-04-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookdetails_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recombooks',
            name='drcode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recombooks',
            name='publisher',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='recombooks',
            name='recomno',
            field=models.CharField(default='20000000000000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='recombooks',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recombooks',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='BookDetails',
        ),
    ]
