# Generated by Django 5.0.4 on 2024-04-16 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_recombooks_drcode_recombooks_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recombooks',
            name='drcode',
        ),
        migrations.RemoveField(
            model_name='recombooks',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='recombooks',
            name='recomisbn',
        ),
        migrations.RemoveField(
            model_name='recombooks',
            name='recomment',
        ),
        migrations.RemoveField(
            model_name='recombooks',
            name='recomno',
        ),
        migrations.AddField(
            model_name='recombooks',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recombooks',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(default='', max_length=8)),
                ('recomment', models.CharField(max_length=2000)),
                ('recomisbn', models.CharField(max_length=13)),
                ('recomno', models.CharField(default='20000000000000000000', max_length=20)),
                ('drcode', models.PositiveIntegerField(default=0)),
                ('recombook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.recombooks')),
            ],
        ),
    ]
